version: '3.7'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - 'config.env'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    env_file:
      - 'config.env'

  app:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - 'config.env'
    ports:
      - 0.0.0.0:443:8443
    networks:
      - gatekeeper
      - default

networks:
  gatekeeper:
    name: gatekeeper_net
