version: '3.7'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql

    env_file:
      - 'config.env'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    env_file:
      - 'config.env'

  http-to-https:
    image: articulate/http-to-https
    restart: always
    ports:
      - 0.0.0.0:80:80
    restart: always

  app:
    stdin_open: true
    tty: true
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - 'config.env'
    ports:
      - 0.0.0.0:443:8443
    networks:
      - gatekeeper
      - default

volumes:
  mysql_data: 


networks:
  gatekeeper:
    name: gatekeeper_net
